# config/config.yaml
database:
  host: "localhost"
  port: 3306
  user: "user1"      # 必须和 docker-compose.yml 里的一致
  password: "112233"  # 必须和 docker-compose.yml 里的一致
  dbname: "go_ai_assistant"
jwt:
  secret_key: "zuguofanrongchangsheng" 
  expire_hours: 72 # Token 有效期（小时）
dashscope:
  api_key: "sk-fe87b648bb1b4ed4baf5d2d0431386cb"

chromadb:
  url: "http://localhost:8000"